# Generated by Django 4.1.7 on 2023-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.fields.IntegerField>/'),
        ),
    ]
