# Generated by Django 4.1.7 on 2023-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='path',
            field=models.CharField(max_length=1000, null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=models.CharField(max_length=1000, null=True, verbose_name='path')),
        ),
    ]
