# Generated by Django 4.1.7 on 2023-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_images_path_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='path',
        ),
        migrations.AddField(
            model_name='images',
            name='image200',
            field=models.ImageField(null=True, upload_to='images/200'),
        ),
        migrations.AddField(
            model_name='images',
            name='image400',
            field=models.ImageField(null=True, upload_to='images/400'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_binary',
            field=models.ImageField(null=True, upload_to='images/binary'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_original',
            field=models.ImageField(null=True, upload_to='images/original'),
        ),
    ]
