# Generated by Django 4.1.7 on 2023-02-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_images_image_remove_images_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image200',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image400',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_binary',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_original',
        ),
    ]
