# Generated by Django 4.1.7 on 2023-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
