# Generated by Django 4.1.7 on 2023-02-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
