# Generated by Django 4.1.7 on 2023-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='link',
            new_name='link1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='thumbnail_size',
        ),
        migrations.AddField(
            model_name='images',
            name='link2',
            field=models.CharField(max_length=1000, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='images',
            name='link3',
            field=models.CharField(max_length=1000, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='images',
            name='link4',
            field=models.CharField(max_length=1000, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='images',
            name='link5',
            field=models.CharField(max_length=1000, null=True, verbose_name='link'),
        ),
    ]
