# Generated by Django 4.1.7 on 2023-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_link_images_link1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='link5',
        ),
    ]
